extends:
  - spectral:oas

rules:
  info-contact: off
  info-license: off
  operation-description: error
  operation-operationId: error
  operation-tags: error

overrides:
  - files:
      - openapi/common-components-v1.yaml
    rules:
      oas3-api-servers: off
      oas3-unused-component: off
